apiVersion: v2
name: dima
version: 1.0.0
type: application
keywords:
  - dima
home: https://github.com/feature-creeps/observability-workshop
sources:
  - https://github.com/feature-creeps/observability-workshop
dependencies:  
  - name: "dima-frontend"
  - name: "dima-imageflip"
  - name: "dima-imagegrayscale"
  - name: "dima-imageholder"
  - name: "dima-imageorchestrator"
  - name: "dima-imageresize"
  - name: "dima-imagerotator"
  - name: "dima-imagethumbnail"
  - name: "dima-mongodb"
  - name: "dima-trafficgen"
    condition: dima-traffic-gen.enabled